# Generated by Django 5.0.1 on 2024-01-28 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('quantité', models.IntegerField(default=0, help_text='Quantité en stock')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_produits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prix', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_C', models.CharField(max_length=100)),
                ('produits', models.ManyToManyField(related_name='categories', to='produits.produits')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['nom_C'],
            },
        ),
        migrations.AddConstraint(
            model_name='produits',
            constraint=models.CheckConstraint(check=models.Q(('prix__gte', 0)), name='prix_non_negative'),
        ),
    ]
